### ISSUE TITLE
error about  PATH set to RVM ruby but GEM_HOM

### ISSUE THREAD

**Issue by maxiaoan** [saasbook/courseware#23]
Hi, there

when I follow this instructions:
`https://github.com/saasbook/courseware/wiki/Setting-up-Cloud9`

this is some errors  about when  I run the command below:
`curl -fsSL c9setup.saasbook.info | sudo bash --login && rvm use 2.4.0 --default`

**below  is output:**
`afaty:~/workspace $ 'curl -fsSL c9setup.saasbook.info | sudo bash --login && rvm use 2.4.0 --default'

Warning: PATH set to RVM ruby but GEM_HOME and/or GEM_PATH not set, see:
    https://github.com/rvm/rvm/issues/3212

Hint: To fix PATH errors try using 'rvmsudo' instead of 'sudo', see:
    https://stackoverflow.com/questions/27784961/received-warning-message-path-set-to-rvm-after-updating-ruby-version-using-rvm/28080063#28080063

**this is another error when I run above command.**

bash: line 1: syntax error near unexpected token `newline'
bash: line 1: `<!DOCTYPE html>

**Comment by tansaku** [comment]
sorry to hear that - I'm not sure that this script is being properly maintained at the moment.

as far as I know c9 already defaults to ruby 2.4.0 so you could just avoid running the script and move on ...

**Comment by maxiaoan** [comment]
> sorry to hear that - I'm not sure that this script is being properly maintained at the moment.
> 
> as far as I know c9 already defaults to ruby 2.4.0 so you could just avoid running the script and move on ...

Thanks for your reply, I just want to follow the tutorials step by step to complete the course,  on my local ubuntu OS system, it works. but on cloud9, there are some errors like above.
